// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeleniumGrid) DeepCopyInto(out *SeleniumGrid) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeleniumGrid.
func (in *SeleniumGrid) DeepCopy() *SeleniumGrid {
	if in == nil {
		return nil
	}
	out := new(SeleniumGrid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeleniumGrid) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeleniumGridList) DeepCopyInto(out *SeleniumGridList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeleniumGrid, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeleniumGridList.
func (in *SeleniumGridList) DeepCopy() *SeleniumGridList {
	if in == nil {
		return nil
	}
	out := new(SeleniumGridList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeleniumGridList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeleniumGridSpec) DeepCopyInto(out *SeleniumGridSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeleniumGridSpec.
func (in *SeleniumGridSpec) DeepCopy() *SeleniumGridSpec {
	if in == nil {
		return nil
	}
	out := new(SeleniumGridSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeleniumGridStatus) DeepCopyInto(out *SeleniumGridStatus) {
	*out = *in
	if in.ChromeNodeList != nil {
		in, out := &in.ChromeNodeList, &out.ChromeNodeList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeleniumGridStatus.
func (in *SeleniumGridStatus) DeepCopy() *SeleniumGridStatus {
	if in == nil {
		return nil
	}
	out := new(SeleniumGridStatus)
	in.DeepCopyInto(out)
	return out
}
